spring.application.name=RecipeBlogApplication

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/db_recipe
spring.datasource.username=root
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

recipe.upload-dir=src/main/resources/static/img/recipes/
